[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "ecco-pipeline"
version = "0.1.0"
description = "ECCO Observation Pipeline"

[tool.setuptools.packages.find]
where = ["."]
include = ["ecco_pipeline*"]